### ISSUE TITLE
Can we make tryfrege "tutorial friendly"

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-interpreter#3] opened 2012-11-13 19:33 UTC
Can we change the tryfrege so that we have a tab "Tutorial" where we can display a tutorial consisting of different pages that can be reached via `Previous` and `Next` buttons?

It would be most ideal if we could just write some wiki pages with some configurable names like `Tutorial-1.md`, `Tutorial-2.md`, etc. so that we do not need to re-deploy once the tutorial changes (which will happen quite often in the beginning).

Also, it would please me most if we could use the markup used here on GitHub or on Stackoverflow which is fairly good. If we could use the GitHub markup the Pros would be that one could use GitHub to edit and (pre)view it.

Now that I write this I wonder if it would be enough to just show the page in the tab and let it use the links that are in there. Of course, the translation from markdown to HTML has to be done somehow, yet I am sure this is a no brainer for people that are more web developers than me (which is to say: more than 0).

**Comment by mmhelloworld** [comment] 2015-11-11 03:19
We experimented with this but found out that it is not of much use as there is not much content and there is already a huge number of tutorials for Haskell out there. This feature has been removed now and I am closing this issue as it is very old. If the issue is still relevant, please reopen or create a new one.

**Closed by mmhelloworld** 2015-11-11 03:19 UTC
